# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRec',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rec1', models.CharField(max_length=200)),
                ('rec2', models.CharField(max_length=200)),
                ('rec3', models.CharField(max_length=200)),
                ('rec4', models.CharField(max_length=200)),
                ('rec5', models.CharField(max_length=200)),
                ('rec6', models.CharField(max_length=200)),
                ('rec7', models.CharField(max_length=200)),
                ('rec8', models.CharField(max_length=200)),
                ('rec9', models.CharField(max_length=200)),
                ('rec10', models.CharField(max_length=200)),
            ],
        ),
    ]
